/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static interfaces.G_Managers.reg;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sir Chikukwa
 */
public class Login extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
java.util.Date date = new java.util.Date();

    long t = date.getTime();
    java.sql.Timestamp Timestamp = new java.sql.Timestamp(t);
    java.sql.Date sqlDate = new java.sql.Date(t);

    public void connect() {
        String filepath = "src/configuration.txt";
        File file = new File(filepath);
        try {
            FileReader fr = null;
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String zp = br.readLine();
            configs.setText(zp);
            String sx = DB_URL + configs.getText();
            configs.setText(sx);

        } catch (IOException ep) {
            JOptionPane.showMessageDialog(null, ep.getMessage());
        }
    }

    public void connect1() {
        String filepath = "src/configuration_1.txt";
        File file = new File(filepath);
        try {
            FileReader fr = null;
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String zp = br.readLine();
            configs2.setText(zp);
            String sx = DB_URL + configs2.getText();
            configs2.setText(sx);

        } catch (IOException ep) {
            JOptionPane.showMessageDialog(null, ep.getMessage());
        }
    }

    int lblTextLength = 0;
  
    int counter = 0;
    String DB_DRIVER = "org.postgresql.Driver";
    String DB_URL = "jdbc:postgresql:";
    String DB_USER;
    String DB_PAS;
    java.sql.Connection con = null;
    java.sql.Statement stm = null;
    java.sql.ResultSet rs = null;
    java.sql.PreparedStatement pst = null;

    public void db_users_connect() {
        String filepath = "src/db_user.txt";
        File file = new File(filepath);
        try {
            FileReader fr = null;
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String zp = br.readLine();
            uname.setText(zp);

        } catch (IOException ep) {
            JOptionPane.showMessageDialog(null, ep.getMessage());
        }
    }

    public void db_password_connect() {
        String filepath = "src/db_pass.txt";
        File file = new File(filepath);
        try {
            FileReader fr = null;
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String zp = br.readLine();
            upass.setText(zp);

        } catch (IOException ep) {
            JOptionPane.showMessageDialog(null, ep.getMessage());
        }
    }

    public Login() {
        //Icon();
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/img/shop.png"));
        this.setLocationRelativeTo(null);
        connect();
        connect1();
        db_users_connect();
        db_password_connect();

    }

    int attempt = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        user = new rojeru_san.RSMTextFull();
        pass = new rojeru_san.RSMPassView();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sa = new javax.swing.JLabel();
        se = new javax.swing.JLabel();
        configs = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        configs2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        home.setFocusable(false);
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setBackground(new java.awt.Color(51, 102, 255));
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setBordeColorFocus(new java.awt.Color(255, 204, 0));
        user.setBotonColor(new java.awt.Color(255, 204, 0));
        user.setCaretColor(new java.awt.Color(255, 204, 0));
        user.setDisabledTextColor(new java.awt.Color(255, 204, 0));
        user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        user.setOpaque(false);
        user.setPlaceholder("enter username");
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 270, -1));

        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBordeColorFocus(new java.awt.Color(255, 204, 0));
        pass.setBordeColorNoFocus(new java.awt.Color(255, 255, 255));
        pass.setBotonColor(new java.awt.Color(255, 204, 0));
        pass.setCaretColor(new java.awt.Color(255, 204, 0));
        pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pass.setOpaque(false);
        pass.setPlaceholder("enter your password");
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 270, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Close CDS");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 120, 40));

        jPanel3.setBackground(new java.awt.Color(255, 207, 52));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dev Login");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 120, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images (4).png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 310));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 250, 316));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Authentication Required");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 10, 380, -1));

        home.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 640, 320));

        sa.setText("jLabel3");
        home.add(sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 114, 80, 0));

        se.setText("jLabel3");
        home.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 74, -1, 0));

        configs.setText("jLabel3");
        home.add(configs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 234, -1, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Currency Dynamics Shell");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        home.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 640, 40));

        uname.setText("jLabel1");
        home.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 54, -1, 0));

        upass.setText("jLabel1");
        home.add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 54, -1, 0));

        configs2.setText("jLabel1");
        home.add(configs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 74, 230, 0));

        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 730));

        setSize(new java.awt.Dimension(1273, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        int key = evt.getKeyCode();
        if (key == 10) {
            if (user.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter username", "Some information missing", JOptionPane.ERROR_MESSAGE);
            }
            if (pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter password", "Some information missing", JOptionPane.ERROR_MESSAGE);
            }
            if (!user.getText().isEmpty() && !pass.getText().isEmpty()) {
                String query = "SELECT fname,lname,position,username,password,region,branch,user_id FROM users where username='" + user.getText() + "' and password='" + pass.getText() + "'";
                DB_USER = uname.getText();
                DB_PAS = upass.getText();
                try {
                    Class.forName(DB_DRIVER);
                    con = DriverManager.getConnection(configs.getText(), DB_USER, DB_PAS);
                    stm = con.createStatement();
                    rs = stm.executeQuery(query);
                    boolean bool = rs.isBeforeFirst();
                    while (rs.next()) {
                        if (bool == true) {
                            String a = rs.getString("fname");
                            String b = rs.getString("lname");
                            String c = rs.getString("position");
                            String d = rs.getString("username");
                            String e = rs.getString("password");
                            String f = rs.getString("region");
                            String h = rs.getString("branch");
                            String k = rs.getString("user_id");
                            if (c.matches("System Administrator") && attempt < 4) {
                                Admininstrator2 adw = new Admininstrator2();
                                adw.setVisible(true);
                                Admininstrator2.name.setText(a.concat(" ").concat(b));
                                Admininstrator2.kms.setText(k);
                                Admininstrator2.configs.setText(configs.getText());
                                this.dispose();
                            }
                            if (c.matches("Regional Manager") && attempt < 4) {
                                G_Managers ad = new G_Managers();
                                ad.setVisible(true);
                                G_Managers.name.setText(a.concat(" ").concat(b));
                                G_Managers.reg.setText(f);
                                G_Managers.b1.setText(f);
                                G_Managers.my_id.setText(k);
                                G_Managers.configs.setText(configs.getText());

                                G_Managers.fa5.addItem(reg.getText());
                                G_Managers.fb5.addItem(reg.getText());
                                G_Managers.fc5.addItem(reg.getText());
                                G_Managers.fd5.addItem(reg.getText());

                                G_Managers.py5.addItem(reg.getText());
                                G_Managers.wy5.addItem(reg.getText());
                                G_Managers.zh5.addItem(reg.getText());
                                G_Managers.px5.addItem(reg.getText());

                                G_Managers.cp1.addItem(reg.getText());
                                G_Managers.opb3.addItem(reg.getText());
                                G_Managers.cg1.addItem(reg.getText());
                                G_Managers.tw3.addItem(reg.getText());

                                this.dispose();
                            }
                            if (c.matches("Developer") && attempt < 4) {
                                Config_Control ad = new Config_Control();
                                ad.setVisible(true);
                                Config_Control.name.setText(a.concat(" ").concat(b));
                                Config_Control.configs.setText(configs.getText());
                                Config_Control.my_id.setText(k);
                                Config_Control.status.setText("Online");
                                this.dispose();
                            }
                            if (c.matches("Finance Personel") && attempt < 4) {
                                Finance_Dep ad = new Finance_Dep();
                                ad.setVisible(true);
                                Finance_Dep.name.setText(a.concat(" ").concat(b));
                                Finance_Dep.my_id.setText(k);
                                Finance_Dep.configs.setText(configs.getText());
                                this.dispose();
                            }
                            if (c.matches("Branch Manager") && attempt < 4) {
                                Supervisors1 ad = new Supervisors1();
                                ad.setVisible(true);
                                Supervisors1.name.setText(a.concat(" ").concat(b));
                                Supervisors1.branch.setText(h);
                                Supervisors1.my_id.setText(k);
                                Supervisors1.a6.setText(f);
                                Supervisors1.configs.setText(configs.getText());

                                this.dispose();
                            }
                            if (c.matches("Strong Room Operator") && attempt < 4) {
                                Operators ad = new Operators();
                                ad.setVisible(true);
                                Operators.name.setText(a.concat(" ").concat(b));
                                Operators.branch.setText(h);
                                Operators.configs.setText(configs.getText());
                                Operators.my_id.setText(k);
                                String queryx = "SELECT currency_name,short_code,base_currency FROM currencies where base_currency='" + true + "'";
                                try {
                                    Class.forName(DB_DRIVER);
                                    con = DriverManager.getConnection(configs.getText(), DB_USER, DB_PAS);
                                    stm = con.createStatement();
                                    rs = stm.executeQuery(queryx);
                                    boolean boolb = rs.isBeforeFirst();
                                    while (rs.next()) {
                                        if (boolb == true) {
                                            String am = rs.getString("short_code");
                                            Operators.phy.setText(am);
                                        }
                                    }
                                    if (boolb == false) {

                                    }

                                } catch (ClassNotFoundException | SQLException ev) {
                                    //JOptionPane.showMessageDialog(null, ev.getMessage(), "Something went wrong", JOptionPane.ERROR_MESSAGE);
                                }
                                this.dispose();
                            }
                            if (c.matches("Counter Clerk") && attempt < 4) {
                                Clerk ad = new Clerk();
                                ad.setVisible(true);
                                Clerk.name.setText(a.concat(" ").concat(b));
                                Clerk.branch.setText(h);
                                Clerk.my_id.setText(k);
                                Clerk.reg.setText(f);
                                Clerk.configs.setText(configs.getText());

                                String queryx = "SELECT currency_name,short_code,base_currency FROM currencies where base_currency='" + true + "'";
                                try {
                                    Class.forName(DB_DRIVER);
                                    con = DriverManager.getConnection(configs.getText(), DB_USER, DB_PAS);
                                    stm = con.createStatement();
                                    rs = stm.executeQuery(queryx);
                                    boolean boolb = rs.isBeforeFirst();
                                    while (rs.next()) {
                                        if (boolb == true) {
                                            String am = rs.getString("short_code");
                                            Clerk.phy.setText(am);
                                        }
                                    }
                                    if (boolb == false) {

                                    }

                                } catch (ClassNotFoundException | SQLException ev) {
                                    //JOptionPane.showMessageDialog(null, ev.getMessage(), "Something went wrong", JOptionPane.ERROR_MESSAGE);
                                }

                                this.dispose();
                            }
                        }
                    }
                    if (bool == false) {
                        if (attempt != 4) {
                            JOptionPane.showMessageDialog(null, "Incorrect credentials", "Authentication failed | Login Attempt " + attempt, JOptionPane.ERROR_MESSAGE);

                        }
                        if (attempt == 3) {
                            JOptionPane.showMessageDialog(null, "You are left with one attempt and if you provide incorrect credentials the system will be terminated", "Authentication failed | Login Attempt " + attempt, JOptionPane.ERROR_MESSAGE);

                        }
                        if (attempt >= 4) {
                            JOptionPane.showMessageDialog(null, "Incorrect credentials, now i'm terminating the system", "Login attempts exceeded " + attempt, JOptionPane.ERROR_MESSAGE);
                            user.setEnabled(false);
                            pass.setEnabled(false);
                            System.exit(5);
                        }
                        attempt++;
                    }

                } catch (ClassNotFoundException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Contact Database Admin", JOptionPane.ERROR_MESSAGE);
                }
            }
        }


    }//GEN-LAST:event_passKeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int input = JOptionPane.showConfirmDialog(null, " Are you sure that you want to close this application", "Providence says....", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == JOptionPane.NO_OPTION) {

        }
        if (input == JOptionPane.YES_OPTION) {
            System.exit(2);

        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        int input = JOptionPane.showConfirmDialog(null, "Please be advised that only the software developer or your system administrator is only allowed\n to proceed with configurration.Are you one of these system super users ?", "Providence says....", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == JOptionPane.NO_OPTION) {

        }
        if (input == JOptionPane.YES_OPTION) {
            Dev_Login dl = new Dev_Login();
            dl.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jLabel4MouseClicked
    int y = 0;
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel configs;
    private javax.swing.JLabel configs2;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private rojeru_san.RSMPassView pass;
    private javax.swing.JLabel sa;
    private javax.swing.JLabel se;
    public static final javax.swing.JLabel uname = new javax.swing.JLabel();
    public static final javax.swing.JLabel upass = new javax.swing.JLabel();
    private rojeru_san.RSMTextFull user;
    // End of variables declaration//GEN-END:variables

}
