/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Sir Chikukwa
 */
public class news extends javax.swing.JFrame {

    /**
     * Creates new form news
     */
    public news() {
        initComponents();
        jocBusyIcon1.setBusy(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jocHyperlinkAction1 = new com.xzq.osc.JocHyperlinkAction();
        jocTrayIcon1 = new com.xzq.osc.JocTrayIcon();
        jocCoverPane1 = new com.xzq.osc.JocCoverPane();
        jocBusyIcon1 = new com.xzq.osc.JocBusyIcon();
        jocAction1 = new com.xzq.osc.JocAction();
        jocModalDialog1 = new com.xzq.osc.JocModalDialog();
        jocPaneGroup1 = new com.xzq.osc.JocPaneGroup();
        jocTableCellRenderer1 = new com.xzq.osc.JocTableCellRenderer();
        jScrollPane1 = new javax.swing.JScrollPane();
        jocSummaryTable1 = new com.xzq.osc.JocSummaryTable();
        jocValueField1 = new com.xzq.osc.JocValueField();
        jocTabbedPane1 = new com.xzq.osc.JocTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jocRangeField1 = new com.xzq.osc.JocRangeField();
        jocMessageLabel1 = new com.xzq.osc.JocMessageLabel();
        jocHyperlink1 = new com.xzq.osc.JocHyperlink();
        jPanel5 = new javax.swing.JPanel();
        jocGroupPane1 = new com.xzq.osc.JocGroupPane();
        jocLabel1 = new com.xzq.osc.JocLabel();
        jocLabel2 = new com.xzq.osc.JocLabel();
        jocLabel3 = new com.xzq.osc.JocLabel();
        jocLabel4 = new com.xzq.osc.JocLabel();
        dm = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jocGregCalendarPane1 = new com.xzq.osc.JocGregCalendarPane();

        jocBusyIcon1.setBusy(true);
        jocBusyIcon1.setDelay(5);

        javax.swing.GroupLayout jocModalDialog1Layout = new javax.swing.GroupLayout(jocModalDialog1.getContentPane());
        jocModalDialog1.getContentPane().setLayout(jocModalDialog1Layout);
        jocModalDialog1Layout.setHorizontalGroup(
            jocModalDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jocModalDialog1Layout.setVerticalGroup(
            jocModalDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jocSummaryTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jocSummaryTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jocSummaryTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 730, 210));

        jocValueField1.setText("jocValueField1");
        getContentPane().add(jocValueField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 193, 165, 34));

        jocTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        jocTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        jocTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        jocTabbedPane1.addTab("tab3", jPanel3);

        getContentPane().add(jocTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 0, -1, 100));
        getContentPane().add(jocRangeField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jocMessageLabel1.setText("jocMessageLabel1");
        getContentPane().add(jocMessageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 382, 130, 33));

        jocHyperlink1.setText("jocHyperlink1");
        getContentPane().add(jocHyperlink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 421, 78, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jocGroupPane1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/opr.png"))); // NOI18N
        jocGroupPane1.setText("Dashboard");

        jocLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setupimg/add_database_32px.png"))); // NOI18N
        jocLabel1.setText("Create database");

        jocLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setupimg/add_database_32px.png"))); // NOI18N
        jocLabel2.setText("Create tables");

        jocLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setupimg/add_database_32px.png"))); // NOI18N
        jocLabel3.setText("Upload to the database");

        jocLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setupimg/add_database_32px.png"))); // NOI18N
        jocLabel4.setText("Create backups");

        javax.swing.GroupLayout jocGroupPane1Layout = new javax.swing.GroupLayout(jocGroupPane1);
        jocGroupPane1.setLayout(jocGroupPane1Layout);
        jocGroupPane1Layout.setHorizontalGroup(
            jocGroupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jocGroupPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jocGroupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jocLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jocLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jocLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jocLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jocGroupPane1Layout.setVerticalGroup(
            jocGroupPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jocGroupPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jocLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jocLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jocLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jocLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jocGroupPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 190));

        dm.setText("jLabel1");
        jPanel5.add(dm, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 140, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 410));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jocGregCalendarPane1.setBackground(new java.awt.Color(255, 255, 255));
        jocGregCalendarPane1.setCellBorderColor(new java.awt.Color(255, 255, 255));
        jocGregCalendarPane1.setRolloverBackground(new java.awt.Color(255, 255, 255));
        jocGregCalendarPane1.setTitleBackground(new java.awt.Color(255, 255, 255));
        jocGregCalendarPane1.setWeekNumberBackground(new java.awt.Color(0, 153, 255));
        getContentPane().add(jocGregCalendarPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 257, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(news.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(news.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(news.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(news.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new news().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dm;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.xzq.osc.JocAction jocAction1;
    private com.xzq.osc.JocBusyIcon jocBusyIcon1;
    private com.xzq.osc.JocCoverPane jocCoverPane1;
    private com.xzq.osc.JocGregCalendarPane jocGregCalendarPane1;
    private com.xzq.osc.JocGroupPane jocGroupPane1;
    private com.xzq.osc.JocHyperlink jocHyperlink1;
    private com.xzq.osc.JocHyperlinkAction jocHyperlinkAction1;
    private com.xzq.osc.JocLabel jocLabel1;
    private com.xzq.osc.JocLabel jocLabel2;
    private com.xzq.osc.JocLabel jocLabel3;
    private com.xzq.osc.JocLabel jocLabel4;
    private com.xzq.osc.JocMessageLabel jocMessageLabel1;
    private com.xzq.osc.JocModalDialog jocModalDialog1;
    private com.xzq.osc.JocPaneGroup jocPaneGroup1;
    private com.xzq.osc.JocRangeField jocRangeField1;
    private com.xzq.osc.JocSummaryTable jocSummaryTable1;
    private com.xzq.osc.JocTabbedPane jocTabbedPane1;
    private com.xzq.osc.JocTableCellRenderer jocTableCellRenderer1;
    private com.xzq.osc.JocTrayIcon jocTrayIcon1;
    private com.xzq.osc.JocValueField jocValueField1;
    // End of variables declaration//GEN-END:variables
}
